unified_mode     'true'
name             'rblogstatter'
maintainer       'redborder'
maintainer_email 'malvarez@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures cookbook-rb-logstatter'
version          '0.0.1'
