unified_mode     'true'
name             'rblogstatter'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures cookbook-rb-logstatter'
version          '0.0.3'
